package bluetooth_tool

const (
	BT_CONNECT_TIMEOUT = 5
	BTNAME_SHX8800     = "walkie-talkie"

	HANDSHAKE_TIMEOUT = 5
	BT_SCAN_TIMEOUT   = 10

	BATTERY_CHARACTERISTIC_UUID           = "2a19"
	MANUFACTURER_CHARACTERISTIC_UUID      = "2a29"
	FIRMWARE_REVISION_CHARACTERISTIC_UUID = "2a26"
	MODEL_NUMBER_CHARACTERISTIC_UUID      = "2a24"
	CHECK_CHARACTERISTIC_UUID             = "ff31"
	RW_CHARACTERISTIC_UUID                = "ffe1"
)

var HANDSHAKE_CODE = []byte{80, 82, 79, 71, 82, 79, 77, 83, 72, 88, 85}
var HANDSHAKE_RESP = 6
