name: goreleaser

on: [push,pull_request]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - uses: bwoodsend/setup-winlibs-action@v1
        id: winlibs-64

      - uses: bwoodsend/setup-winlibs-action@v1
        id: winlibs-32
        with:
          architecture: i686

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}