name: goreleaser

on: [ push,pull_request ]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - uses: bwoodsend/setup-winlibs-action@v1
        id: winlibs-64

      - name: Run Build
        run: .github\workflows\build.bat

      - name: Run Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tmp/*
          token: ${{ secrets.TOKEN }}